### ISSUE TITLE
MPI using two or more nodes for one process

### ISSUE THREAD

**Issue by rafaeltiveron** [brianjimenez/lightdock#24]
Hi again, Bryan

I would like to know how to put a uniq process to run in two or more nodes, using two or more threads? I've seen mpi4py is one of the dependences.

Thank you

**Comment by brianjimenez** [comment]
In `bin/simulation` there is a main `controller.py` file in charge of starting the simulation through multiprocessing `docking_multiprocessing.py` or MPI `docking_mpi.py`. If you use the flag `-mpi`, LightDock should use the docking_mpi.py code. It's been a long time since I had access to a machine with multiple nodes, so take that code as experimental and please let me know if it works for you.
